name: websiteTY
on: push
jobs:
  building-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Clean
        continue-on-error: true
        run: docker stop website06 && docker rm website06 && docker rmi tzeyaang/websiteTY
      - name: Build Image 
        run: docker build -t tzeyaang/websiteTY .
      - name: List Image
        run: docker images
      - name: Upload image to Docker Hub
        run: docker push tzeyaang/websiteTY
      - name: Deploy WebsiteTY
        run: docker run -d --name=websiteTY -p 8080:80 tzeyaang/websiteTY
